# branches:
#   only:
#   - master
os: linux
dist: xenial
language: generic

cache:
  timeout: 1000
  directories:
    - _opam
    - dune_network/_opam

before_install:
- sh travis-scripts/prepare-ubuntu.sh

install:
- export OPAMYES=1
- sh travis-scripts/prepare-opam.sh
- bash travis-scripts/build-dune.sh
- source travis-scripts/start-dune-sandbox.sh

script:
- eval `opam config env`
- make
- make tests-mini
- make tests
- make tests-love
- make rev-tests

after_script:
- bash travis-scripts/stop-dune-sandbox.sh
